# SETTINGS

# WARNING: DO NOT CHANGE THE TYPE HINTS OF THE VARIABLES!!!
IS_DEBUG: bool = True
ANDROID_CLIPBOARD_TIMEOUT_SECONDS: int = 5
BLACKLISTED_UNICODE_CATEGORIES: set[str] = {'Cs', 'Cc', 'Cf', 'Mn', 'Mc'}
UNICODE_HIGHEST_CODE_PONT: int = 0x10FFFF
LOGS_ERROR_GENERIC_PREFIX: str = 'ERROR'
LOGS_ERROR_ASSERTION_PREFIX: str = 'ASSERTION FAIL'
LOGS_DEBUG_PREFIX: str = 'DEBUG'
LOGS_WARNING_PREFIX: str = 'WARNING'
LOGS_SEPARATOR: str = ' | '
LOGS_LIGHT_ARCHIVE_UNKNOWN_NAME = "Unknown"
RECURSION_LIMIT: int = 10000
COPY_BLOCK_SIZE_BYTES: int = 1024 * 1024 * 16
LIGHT_ARCHIVE_UNPACK_EXPECTED_MAX_NAME_BYTES: int = 1000
LIGHT_ARCHIVE_UNPACK_EXPECTED_MAX_ENCODED_INT_BYTES: int = 100